spring.config.activate.on-profile=dev
server.port=8080

# MongoDB Information
spring.data.mongodb.database=MLS
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=
spring.data.mongodb.password=

# Redis Information
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=10000
spring.data.redis.lettuce.pool.max-active=200
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=0

# Api Context-path
server.servlet.context-path=/api/v1

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Spring devtools
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

# Sa-Token
sa-token.token-name=MLS-Token
sa-token.timeout=864000
sa-token.active-timeout=-1
sa-token.is-concurrent=true
sa-token.is-share=false
sa-token.token-style=random-128
sa-token.is-log=true
